### ISSUE TITLE
Not working for android

### ISSUE THREAD

**Issue by ThakkarKhushbu** [socketio/socket.io-client#1284]
not working for android device

**Comment by Luomusha** [comment]
same problem in react-native 0.59

**Comment by anttirauh** [comment]
I can confirm: socket.io-client is not working in React Native Android release builds. It can't connect to socket.io server. Works fine when running in debug mode but not in release builds.

It was working with older RN versions, but gone broken in RN 0.57.4.

This issue is important to fix, because Google do not accept new Android releases without 64 bit support. And 64 bit support comes with RN 0.59 

==> this issue currently prevents releasing/updating RN Android apps which use socket.io library

Saa also: https://github.com/facebook/react-native/issues/22043

**Comment by darrachequesne** [comment]
Please see an example with React Native here: https://github.com/socketio/socket.io/tree/master/examples/react-native
