### ISSUE TITLE
Doesn't work on react-native production mode 

### ISSUE THREAD

**Issue by iarif4u** [socketio/socket.io-client#1335]
i have a problem with react-native and socket io. when i connect socket server on debugging mode it's working fine but when i connect on production mode it doesn't work even doesn't throw any exception.
server.js
var app = require('express')();
var server = require('http').Server(app);

//config socket server
const io = require('socket.io')(server);

//make connection to client
io.of('/').on('connection', (client, res) => {
    //client soket id
    console.log('A client connected');
});
server.listen(3000);

App.js
import React, { Fragment, useEffect } from 'react';
import {SafeAreaView,StyleSheet,ScrollView,View,Text,StatusBar} from 'react-native';

import SocketIOClient from 'socket.io-client'

class App extends React.Component {
constructor(props) {
this.state = {
   endpoint: "http://10.131.232.103:3000"
};
this.socket = SocketIOClient(endpoint);
this.socket.on('connected', () => {
console.log('socket connected.....');

})
}
-----------
-----------
}

**Comment by saimemre** [comment]
same problem

**Comment by Jaquedeveloper** [comment]
Any fixes for it? Any suggestions?

**Comment by douglasduartetb** [comment]
I recommend this example, https://github.com/expo/examples/tree/master/with-socket-io, works for me

**Comment by iarif4u** [comment]
ohh, i find the solutions
just add 
android:usesCleartextTraffic="true"
in application tag on AndroidManifest.xml file

**Comment by neosarchizo** [comment]
@iarif4u It works!!
- react-native : 0.64.1
- socket.io-client : ^4.1.3

**Comment by DDarkLexs** [comment]
I'm encountering an error while using `socket.io-client` in production mode within `react-native`. When attempting to establish a connection, the following error is displayed: `{"type": "TransportError", "description":0}`. Notably, this issue doesn't occur in development mode.

**Error Details:**

- **Error Type:** `TransportError`
- **Description:** `0`

**Steps to Reproduce:**

1. Run the application in production mode.
2. Attempt to establish a connection using `socket.io-client`.

**Expected Behavior:**

The `socket.io-client` should connect without encountering any errors in production mode, similar to its behavior in development mode.

**Additional Context:**

- Version of `react-native`: [Insert Version Number]
- Version of `socket.io-client`: [Insert Version Number]
- Any other relevant information or configurations that might be affecting this issue.

**Potential Solutions Attempted:**

- [List any steps you've already taken to address or investigate the problem, if applicable]

**Request for Assistance:**

I would greatly appreciate any insights or guidance to resolve this issue in production mode. Any help or suggestions on resolving this issue would be immensely helpful. Thank you in advance for your assistance!
