### ISSUE TITLE
2.3.0 with mobile error

### ISSUE THREAD

**Issue by lichenabson** [socketio/socket.io-client#1340]
you will get a error 'SyntaxError: Unexpected identifier 'index' with socket.io-client 2.3.0 in mobile
![image](https://user-images.githubusercontent.com/20200267/68912091-0b094d00-0792-11ea-9a96-0ebc1769654c.png)
then i success with socket.io-client 2.2.0

**Comment by lichenabson** [comment]
env: ios 9. 3/ipnone6s/safari

**Comment by christosv94** [comment]
#1328 It is exactly the same issue as here that exists on old versions of safari as well. The only current solution is to downgrade to 2.2.0

**Comment by radinmoradi** [comment]
در تاریخ سه‌شنبه ۲۶ نوامبر ۲۰۱۹،‏ ۱۸:۵۵ Christakis Vasiliou <
notifications@github.com> نوشت:

**Comment by radinmoradi** [comment]
در تاریخ جمعه ۱۵ نوامبر ۲۰۱۹،‏ ۵:۵۸ lichenabson <notifications@github.com>
نوشت:

**Comment by darrachequesne** [comment]
The `debug` dependency was reverted to `3.1.0`, which does not need to be transpiled. Released in [2.3.1](https://github.com/socketio/socket.io-client/releases/tag/2.3.1).

Please note that you can also use the [webpack-remove-debug](https://github.com/johngodley/webpack-remove-debug) plugin, in order to remove any call to the debug dependency.
