### ISSUE TITLE
Why does socket.io-client get browser's Websocket like this ?

### ISSUE THREAD

**Issue by qiulang** [socketio/socket.io-client#1357]
### You want to:

* [x] request a *feature*

Hi, my request is more about a document request. I did ask at stackoverflow and didn't get an answer. 

So why does socket.io-client get browser's Websocket like this

```
var BrowserWebSocket, NodeWebSocket;

if (typeof WebSocket !== 'undefined') {
  BrowserWebSocket = WebSocket;
} else if (typeof self !== 'undefined') {

  //Is it possbile to run into BrowserWebSocket = self.WebSocket ?

  BrowserWebSocket = self.WebSocket || self.MozWebSocket;
}

if (typeof window === 'undefined') {
  try {
    NodeWebSocket = require('ws');
  } catch (e) { }
}
...
```

1. I understand Firefox's Websocket called MozWebSocket
2. I think using `if (typeof self !== 'undefined')` instead of `if (typeof window !== 'undefined')` is to check window and web worker 

What I don't understand is is it possible to run into `BrowserWebSocket = self.WebSocket`, i.e. typeof WebSocket == 'undefined' but self.WebSocket exists ?

My second question is how does socket.io-client or socket.io generate this part of code or any browser related websocket codes ? I check code in lib, I check the gulpfile but I still can't figure out how. I noticed https://github.com/socketio/engine.io-client has browser websocket code. But I can't figure out how does that build into socket.io-client code.

So can socket.io-client add some document about that ?

Thanks!

**Comment by darrachequesne** [comment]
For future readers:

The code to create a WebSocket instance was indeed a bit weird due to several hacks to make it work on all platforms.

We have simplified it a bit in Engine.IO v4 / Socket.IO v3:

- https://github.com/socketio/engine.io-client/blob/4.1.1/lib/transports/websocket.js#L6-L10
- https://github.com/socketio/engine.io-client/blob/4.1.1/lib/transports/websocket-constructor.js
- https://github.com/socketio/engine.io-client/blob/4.1.1/lib/transports/websocket-constructor.browser.js
- https://github.com/socketio/engine.io-client/blob/4.1.1/package.json#L72
