### ISSUE TITLE
Socket.Io-Client is not working on Android

### ISSUE THREAD

**Issue by AGurindapalli** [socketio/socket.io-client#1421]
@darrachequesne not working on Android.. I have updated engine.io-client to 4.0.4. 
react-native : 0.63.4
socket.io-client:3.0.3
socket.io: 3.0.3

I have created a Hook. It's working Good in IOS.

`import {useEffect, useRef} from 'react';
import io from 'socket.io-client';
import {getUniqueId} from 'react-native-device-info';
import { MessageReq } from '../Types/chat';

const useSocket = () => {
  const ref = useRef<SocketIOClient.Socket>();
  const sendChat = (req: MessageReq) => {
    ref.current!.emit('sendMessage', req);
  };

  const setUpRoom = (userGuid: string | null) => {
    const deviceId = getUniqueId();
   const userGuid='xyz';
    console.log(ref.current!.emit('online', {deviceId, userGuid}));
    ref.current!.emit('online', {deviceId, userGuid});
  };
  useEffect(() => {
    console.log('here');
    const socket = io('http://localhost:3000', {reconnection:true,});
    ref.current = socket;
  }, []);
  return {
    sendChat,
    setUpRoom,
  };
};
export default useSocket;`

Log:
<img width="620" alt="Screenshot 2020-12-03 at 1 17 15 PM" src="https://user-images.githubusercontent.com/30103626/100979652-13cdec00-356a-11eb-9849-a1a444fbe756.png">

_Originally posted by @AGurindapalli in https://github.com/socketio/socket.io-client/issues/1411#issuecomment-737726037_

**Comment by darrachequesne** [comment]
If you are testing on a real device, I think `localhost:3000` might be wrong. Is there a domain/IP address your server is exposed on? Maybe `192.168.x.x` on a local subnet?

More information here: https://github.com/socketio/socket.io/tree/master/examples/react-native

**Comment by RahulRijhwani** [comment]
Face same issue 
You find any solution? @AGurindapalli

**Comment by mabopoi** [comment]
Same problem around here. Using `192.168.x.x` didn't help.
I'm using socket.io-client@3.0.4 and engine.io-client@4.0.5

**Comment by sbsujith** [comment]
Same connection timeout issue in Mac for both android device and ios simulator. 
```
const socket = io('http://127.0.0.1:3030', {
  transports: ['websocket'],
  forceNew: true,
  upgrade: false,
});
```
Successfully connect to server using restful connection though. So looks like some thing to do with socket.io-client

 socket.io-client@3.0.4
 engine.io-client@4.0.5 
react-native@0.63.3

Any fix would be helpful.

**Comment by RahulRijhwani** [comment]
I got solution with just downgrade the version.
I install **npm install socket.io-client@2.3.0** I mean 2.3.0 version and successfully connect

**Comment by mabopoi** [comment]
Using 2.3.0 version on my app didn't work neither. It returned this error: 
`Unable to resolve "../util" from "node_modules\engine.io-client\lib\transports\polling-xhr.js"`

**Comment by RahulRijhwani** [comment]
@mabopoi I also face this issue but I got solution 
first uninstall old library first then try **npm install socket.io-client@2.3.0**

**Comment by sbsujith** [comment]
> @mabopoi I also face this issue but I got solution
> first uninstall old library first then try **npm install socket.io-client@2.3.0**

Thanks.
It worked for me too. Following are the working versions
socket.io-client@2.3.0
engine.io-client@3.4.4 ( installs along with socket.io-client)
react-native@0.63.3

**Comment by JanikBuecher** [comment]
@sbsujith @RahulRijhwani  what do you mean with uninstall old library?

**Comment by mabopoi** [comment]
> @mabopoi I also face this issue but I got solution
> first uninstall old library first then try **npm install socket.io-client@2.3.0**

That's what I did and the error I mentioned before was returned. 
Did you do something else apart from uninstalling the newest version?

**Comment by fkurniaw** [comment]
I have a similar issue as well on react-native v0.63.2 (socket.io-client v3.0.4). iOS is able to maintain a persistent connection with the socket.io server, but i intermittently get a `TRANSPORT ERROR` on android about every ~7 seconds or so. which results in the socket connection

![image](https://user-images.githubusercontent.com/18754153/103161368-bbb78d80-4795-11eb-9fa1-9e69a571c295.png)

(ignore the log in between the nginx logs; that was for periodically logging the list of connected sockets every 5 seconds)

Based on the nginx logs, the android socket.io client disconnects quite regularly, and it seems like it's an issue related to how react-native implements XHR on android. I've had issues with using SSEs on android react-native due to discrepancies between how xhr polling is done between iOS and android on react-native, and my original solution

I haven't had the chance to expose socket.io-client's java implementation on react-native yet, but if that client manages to maintain a persistent connection, im strongly feeling this is an xhr-related issue with how react-native implements the Network library on android

**Comment by daanielcruz** [comment]
> I got solution with just downgrade the version.
> I install **npm install socket.io-client@2.3.0** I mean 2.3.0 version and successfully connect

Its worked for me.

**Comment by shrynshjn** [comment]
Anyone got a solution?
Instead of connecting as  a socket, my server is getting a GET request, and the socket never connects. I have tried version 2.1.1, 2.3.0 and 3.0.4

my server logs
![image](https://user-images.githubusercontent.com/30545482/103450401-c7e2a400-4cdb-11eb-96ce-de97cb7be285.png)

**Comment by bcgoodmate** [comment]
Make sure to use the latest version of socket.io in your web server.
Web Server: socket.io@3.1.0
React Native App: socket.io-client@3.1.0

**Comment by sp4wnx** [comment]
I've installed Socket.io 3.1.0, ReactNative 0.63.4 and never gets connected, always "connected: false", but works perfectly on Web Version.
Anyone have any ideas?

**Comment by leandrodalvi** [comment]
> If you are testing on a real device, I think `localhost:3000` might be wrong. Is there a domain/IP address your server is exposed on? Maybe `192.168.x.x` on a local subnet?
> 
> More information here: https://github.com/socketio/socket.io/tree/master/examples/react-native

The simplest answer was the best. Thank you, m8

**Comment by fanysoft** [comment]
OMG, I spent 10 hours debugging this. Downgrade to npm install socket.io-client@2.3.0  really work. On emulator you can usehttp://10.0.2.2:port or http://192.168.1.101:port / both working

**Comment by neilyoung** [comment]
Yeah, debugging really doesn't help much here. I luckily didn't take that long. See https://github.com/socketio/socket.io-client/issues/1452 also.

A 2.x client needs a 2.x server. I find that unfortunate, TBH

**Comment by eyalyoli** [comment]
I know that version 2.4.0 works fine up to RN 0.63

**Comment by ibrahimkanber** [comment]
@darrachequesne thank you for your answer. It works and life is life saver.

**Comment by ginxx009** [comment]
anyone who's having trouble my workaround for me is this
`const socket = io('http://yourlocalip:3000', {
    transports: ['websocket'],
    jsonp:false,
    forceNew: true,
  });`

then try restarting your server connection and restart your app

    "socket.io-client": "^4.1.3"
    "react-native": "0.64.2",

**Comment by darrachequesne** [comment]
@ginxx009 to add some details to your suggestion:

- `transports: ['websocket']` disables HTTP long-polling (which may or may not be what you want)
- `jsonp:false` disallow JSONP polling, for browsers that do not support XMLHttpRequest (like IE9)
- `forceNew: true` forces the creation of a low-level connection, instead of reusing the previous one

Reference: https://socket.io/docs/v4/client-initialization/#Options

If you need to disable HTTP long-polling for the connection to be established, there are two possible explanations:
- CORS: https://socket.io/docs/v4/troubleshooting-connection-issues/#The-server-does-not-send-the-necessary-CORS-headers
- sticky sessions: https://socket.io/docs/v4/troubleshooting-connection-issues/#You-didn%E2%80%99t-enable-sticky-sessions-in-a-multi-server-setup

Please check the example with React native here: https://github.com/socketio/socket.io/tree/master/examples/react-native

**Comment by ginxx009** [comment]
@daanielcruz I thought socket.io is working properly on mobile but I face a problem where in I have 2 different application 

Application A is working on emitting the data to the server like this

`socket.emit("user app info", dataInfo);`

Server
`socket.on("user app info", dataInfo => {
//         console.log(dataInfo);
//         io.emit("user app info", dataInfo);
//     });`

Application B 
`socket.on("user app info", dataInfo => console.log(dataInfo));` //-> This don't work and can't get the data from the server

**Comment by hussainsherwani** [comment]
@ginxx009  did you find any solution, facing the same issue as you described , Thanks in advance

**Comment by ginxx009** [comment]
> @ginxx009 did you find any solution, facing the same issue as you described but for me I am not getting the message on Application A, in my case these is only application A and server

I moved on and go with firebase. Got no choice.

**Comment by darrachequesne** [comment]
@ginxx009 sorry you didn't find a solution to your issue.

For future readers, react native is totally supported, you can find an example here: https://github.com/socketio/socket.io/tree/master/examples/react-native

**Comment by slassen** [comment]
> anyone who's having trouble my workaround for me is this `const socket = io('http://yourlocalip:3000', { transports: ['websocket'], jsonp:false, forceNew: true, });`
> 
> then try restarting your server connection and restart your app
> 
> ```
> "socket.io-client": "^4.1.3"
> "react-native": "0.64.2",
> ```

I'm not sure how you figured this one out but TYVM! Works for me like this.
