### ISSUE TITLE
Client socket.disconnect does not stop reconnection attempts

### ISSUE THREAD

**Issue by GKTheOne** [socketio/socket.io-client#737]
Scenario one:
. client gets 401 response from server when connecting
. connect_error handler (mostly) gets called
    (Firefox console usually does not show console.log output on first page load - reload and it's fine, so assuming "always" but saying "mostly" jic)
. connect_error handler calls socket.disconnect();
. client attempts to reconnect shortly thereafter

Scenario two:
. server (netty-socketio) gets connection attempt
. server rejects based on authorisation (401 response)
. server disconnects client
. client connect_error handler fires
. client attempts reconnect shortly thereafter

I'm not too worried about scenario two (because it uses the probably unsupported netty-socketio), it's just there to point out the problem is the continuous reconnection.

The main problem is that there appears to be no way to have the client code stop reconnection attempts.

This is leading to much frustration as I don't want users spamming my logs with unauthorised connection messages every ~5 seconds. (Just one message is fine though :) )

Any ideas, please?

**Comment by sSeewald** [comment]
There is a problem after disconnect(). When you call connect() again the reconnection is not working anymore. The main problems are that in the method "Manager.prototype.reconnect" a variable "this.reconnecting" is tested to be true. This is set when i call socket.disconnect(). But after a socket.connect() it is never be reseted. Imho this should be initialized when a socket is opened or connect() is called because this is undefined in the first run.

What makes it tick again:
```
socket.disconnect();
socket.io.reconnecting = undefined; <- false should be the initial value
socket.io._reconnection = true;
socket.connect();
```
