### ISSUE TITLE
socket.connected sometimes false after reconnect

### ISSUE THREAD

**Issue by csulok** [socketio/socket.io-client#831]
Using socket.io 1.2.1, I have a bit of code that handles various updates on the UI after a disconnect/reconnect, and I noticed an issue during reconnect testing. Eventually I found it to be related to assuming socket.connected is true after a reconnect event, but sometimes it's false. Here's how I was able to spot the issue:

``` javascript
socket.on("reconnect", function() {
  console.log(socket.connected);
});
```

I still don't know what decides the value, although I _feel_ it has something to do with timeouts and heartbeats and stuff. If that's relevant, my current settings are:

``` javascript
io.set("heartbeat interval", 8000);
io.set("heartbeat timeout", 10000);
```

and

``` javascript
io.connect("/" + nsp, {
  "autoConnect": false,
  "reconnection": true,
  "timeout": 5000
});
```

Anyhow I expect socket.connected to be true after both a connect and a reconnect event, and I'd like to know why I'm wrong on that :)

**Comment by davidrinnan** [comment]
In my own case that can happen due to a reconnect happening in a new
connection.
I.e the old is still there, not yet removed, e.g. waiting for the timeout
to happen.

But I guess that comes down to my own handling of connected clients, rather
than socket.io it self.

**Comment by PritamUpadhyay** [comment]
I was facing the same issue as this. I handled it by closing connection manually as @davidrinnan  said up in his comment. Check with this solution...

**Comment by darrachequesne** [comment]
For future readers:

Yes, this weird behavior was due to the fact that the "reconnect" event is an event of the Manager (which means the low-level connection was established), but the Socket.IO connection may not be up yet (the `connect` event of the Socket).

We have fixed this in Socket.IO v3: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#The-Socket-instance-will-no-longer-forward-the-events-emitted-by-its-Manager

More information here: https://socket.io/docs/v3/client-socket-instance/#Lifecycle
