### ISSUE TITLE
socket.io polling helpless for redirects

### ISSUE THREAD

**Issue by zevero** [socketio/socket.io-client#854]
Because of stupid company policy, I am behind some https secure login thing, which does not allow me to upgrade to websockets, leaving me with polling.
When I type in username and email I get a session for one or two hours and everything is alright. But when the session is over socket.io turns wild.
![socket](https://cloud.githubusercontent.com/assets/2234140/8271911/19d29c70-1830-11e5-8db8-1be70b6e7c63.png)
Green is normal polling. The blue dots are 25000 requests.
Socket.io is trying really hard, but is helpless when beeing redirected by a 302 receiving the login form, which is cached 304.

Is there a way to detect this?

**Comment by tecnogram888** [comment]
socket.io will emit a 'reconnecting' event when it attempts reconnection so you can create an event handler that keeps track of the pace of reconnects. 
You can also prevent this I believe by setting reconnectionDelay to some large value: I suspect you might have set it thinking that it counts in seconds but it counts in milliseconds so if it's doing 25000 requests perhaps you put in 1 instead of 1000 for 1 second delays.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
