### ISSUE TITLE
uint8Array is not defined

### ISSUE THREAD

**Issue by vshy108** [socketio/socket.io-client#979]
When I am using version 1.4.8 on React Native 0.28.0, error as title is popped out but this problem does not exist if I using the version 1.4.6 on the same React Native.

**Comment by tjni** [comment]
I have never used React Native, but this looks related to socketio/engine.io#407. I supplied a PR that attempts to fix this, and it's waiting to be merged: socketio/engine.io-parser#58.

**Comment by leenux** [comment]
Same problem +1
// Use a lookup table to find the index.
  var lookup = new Uint8Array(256);  <===this point
  for (var i = 0; i < chars.length; i++) {
    lookup[chars.charCodeAt(i)] = i;
  }

**Comment by plantain-00** [comment]
I get the error in IE8

**Comment by alanclarke** [comment]
also happens in ie9

**Comment by mohitgangrade** [comment]
I am getting the same error on IE<=9

**Comment by mohitgangrade** [comment]
Hey guys,
This just fixed the problem for me. I added this polyfill to my script:
https://github.com/inexorabletash/polyfill/blob/master/typedarray.js

It works.

If you add this polyfill and try socket.io in IE8, you will see another error, "Object doesn't support property or method 'addEventListener'".

I don't need to care about IE8 because our web application only needs to support IE9+ =D

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-parser/pull/58
